### ISSUE TITLE
🔮[RFC]: Design: OpenIM Deployment Infrastructure

### ISSUE THREAD

**Issue by cubxxw** [openimsdk/open-im-server#1204]
### Draft Design: OpenIM Deployment Infrastructure

------

#### **I. Overview**

This draft outlines the design for deploying the OpenIM infrastructure utilizing Helm Charts for efficient, reproducible, and scalable deployments. The design encapsulates the deployment scripts of various repositories and aligns with the structural and configurational needs of each module. The main components are categorized into OpenIM Server, OpenIM Chat, OpenIM Web, and respective middleware modules.

#### **II. Directory Structure**

A well-organized directory structure is crucial for managing the charts and configurations. Below is the proposed structure:

```
my-app/
│
├── charts/         
│   ├── openim-server/
│   ├── openim-chat/
│   └── openim-web/
├── middleware/
│   ├── im-mysql/
│   ├── im-mongodb/
│   ├── im-kafka/
│   ├── im-redis/
│   └── im-minio/
├── values.yaml    
└── Chart.yaml      
```

#### **III. Dependency Management**

Dependencies such as MySQL, Redis, MongoDB, etc., will be declared in the `Chart.yaml` file with specified versions and repositories. Here's an example:

```
dependencies:
- name: mysql
  version: "x.x.x"
  repository: "https://charts.bitnami.com/bitnami"
- name: redis
  version: "x.x.x"
  repository: "https://charts.bitnami.com/bitnami"
# ... other dependencies
```

> In case of deployment issues within China, specify domestic image repositories in the `values.yaml` file.

#### **IV. Configuration Management**

Default configuration values will be defined in the `values.yaml` file, including database credentials, middleware configurations, and business-related configurations.

```
openim-server:
  replicaCount: 1
  ...

openim-chat:
  replicaCount: 2
  ...

openim-web:
  replicaCount: 2
  ...

mysql:
  mysqlRootPassword: your-password
  mysqlDatabase: your-database
  ...

# ... other configurations
```

#### **V. Kubernetes Template Files**

Under the `templates/` directory, create respective Kubernetes configuration file templates (e.g., Deployment, Service) for each business module.

#### **VI. Version and Repository Management**

+ A single branch in the GitHub repository represents a stable release of OpenIM, containing charts for `openim-server`, `openim-chat`, `openim-web`, and middleware configurations.
+ All chart sources are managed on GitHub, with different branches managing different versions. A branch correlates to a stable backend release of the entire OpenIM.
+ For middleware charts, configurations mainly involve account info and initialization configurations. These can be managed outside GitHub, maintaining only the account and initialization info on GitHub.

#### **VII. Image Build and Deployment Workflow**

+ Images are auto-generated from GitHub, and on a new business code branch release or significant bug fix, synchronization to the chart GitHub repository, and then to the chart repo repository occurs.
+ In dev and test environments, manual image compilation and pushing to respective repositories is carried out, for instance, `registry.cn-shenzhen.aliyuncs.com/huanglin_hub/admin-api:dev` & `registry.cn-shenzhen.aliyuncs.com/huanglin_hub/admin-api:test`, followed by a restart of the corresponding module's pod.
+ For `minio-api`, a prefix is added to the generated URLs on the client-side while the backend remains unchanged, allowing the system to operate without a domain name requirement.
