### ISSUE TITLE
🤖Failing-test: Unable to send audio and video files

### ISSUE THREAD

**Issue by tzhzz0721** [openimsdk/open-im-server#1264]
### Which job are failing?

在android和网页版客户端上发送，音视频媒体或其他文件时发送失败，只能发送文本消息。

### Which test are failing?

```
## 执行check-all.sh有下面的错误信息
[root@localhost scripts]# ./check-all.sh 

# Begin to check all openim service
+-------------------------+----------+
| Service Name            | Port     |
+-------------------------+----------+
| openim-user             | 10110    |
| openim-friend           | 10120    |
| openim-msg              | 10130    |
| openim-msg-gateway      | 10140    |
| openim-group            | 10150    |
| openim-auth             | 10160    |
| openim-push             | 10170    |
| openim-conversation     | 10180    |
| openim-third            | 10190    |
| openim-api              | 10002    |
| openim-ws               | 10001    |
+-------------------------+----------+
+-------------------------+----------+
| Service Name            | Port     |
+-------------------------+----------+
| mysql                   | 13306    |
| redis                   | 16379    |
| zookeeper               | 12181    |
| kafka                   | 19094    |
| mongodb                 | 37017    |
| minio                   | 10005    |
+-------------------------+----------+
++ The port being checked: 10110 10120 10130 10140 10150 10160 10170 10180 10190 10002 10001

## Check all dependent service ports
+++ The port being checked: 13306 16379 12181 19094 37017 10005
 2023-10-23 09:51:08  The environment is outside the container 
Checking ports: 13306 16379 12181 19094 37017 10005

### Started ports:
Port 13306 - Command: docker-proxy, PID: 1142542, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 16379 - Command: docker-proxy, PID: 1142111, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 12181 - Command: docker-proxy, PID: 1142158, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 19094 - Command: docker-proxy, PID: 1142284, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 37017 - Command: docker-proxy, PID: 1146554, FD: 4, Started: Fri Oct 20 15:24:11 2023
Port 10005 - Command: docker-proxy, PID: 1142135, FD: 4, Started: Fri Oct 20 15:24:03 2023
[success 1023 09:51:09] ==>  All specified processes are running.
++++ Check all dependent service ports successfully !

## Check OpenIM service name
!!! [1023 09:51:09] Call tree:
!!! [1023 09:51:09]  1: ./install/openim-msgtransfer.sh:154 openim::msgtransfer::check(...)
!!! [1023 09:51:09]  2: ./check-all.sh:80 source(...)
!!! Error in ./install/openim-msgtransfer.sh:66 
  Error in ./install/openim-msgtransfer.sh:66. '((i<4-1))' exited with status 1
Call stack:
  1: ./install/openim-msgtransfer.sh:66 openim::msgtransfer::check(...)
  2: ./install/openim-msgtransfer.sh:154 source(...)
  3: ./check-all.sh:80 main(...)
Exiting with status 1
```

### Since when has it been failing?

客户端发送音视频或本地文件时，发送失败。

### Testgrid link

```bash

# Begin to check all openim service

## Check all dependent service ports
Checking ports: 13306 16379 12181 19094 37017 10005

### Started ports:
Port 13306 - Command: docker-proxy, PID: 1142542, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 16379 - Command: docker-proxy, PID: 1142111, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 12181 - Command: docker-proxy, PID: 1142158, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 19094 - Command: docker-proxy, PID: 1142284, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 37017 - Command: docker-proxy, PID: 1146554, FD: 4, Started: Fri Oct 20 15:24:11 2023
Port 10005 - Command: docker-proxy, PID: 1142135, FD: 4, Started: Fri Oct 20 15:24:03 2023
[32m[success 1023 09:03:26] [0m==>  All specified processes are running.

## Check OpenIM service name
!!! [1023 09:03:26] Call tree:
!!! [1023 09:03:26]  1: ./install/openim-msgtransfer.sh:154 openim::msgtransfer::check(...)
!!! [1023 09:03:26]  2: ./check-all.sh:80 source(...)
[31m!!! Error in ./install/openim-msgtransfer.sh:66 [0m
  Error in ./install/openim-msgtransfer.sh:66. '((i<4-1))' exited with status 1
Call stack:
  1: ./install/openim-msgtransfer.sh:66 openim::msgtransfer::check(...)
  2: ./install/openim-msgtransfer.sh:154 source(...)
  3: ./check-all.sh:80 main(...)
Exiting with status 1

# Begin to check all openim service

## Check all dependent service ports
Checking ports: 13306 16379 12181 19094 37017 10005

### Started ports:
Port 13306 - Command: docker-proxy, PID: 1142542, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 16379 - Command: docker-proxy, PID: 1142111, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 12181 - Command: docker-proxy, PID: 1142158, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 19094 - Command: docker-proxy, PID: 1142284, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 37017 - Command: docker-proxy, PID: 1146554, FD: 4, Started: Fri Oct 20 15:24:11 2023
Port 10005 - Command: docker-proxy, PID: 1142135, FD: 4, Started: Fri Oct 20 15:24:03 2023
[32m[success 1023 09:50:17] [0m==>  All specified processes are running.

## Check OpenIM service name
!!! [1023 09:50:17] Call tree:
!!! [1023 09:50:17]  1: ./install/openim-msgtransfer.sh:154 openim::msgtransfer::check(...)
!!! [1023 09:50:17]  2: ./check-all.sh:80 source(...)
[31m!!! Error in ./install/openim-msgtransfer.sh:66 [0m
  Error in ./install/openim-msgtransfer.sh:66. '((i<4-1))' exited with status 1
Call stack:
  1: ./install/openim-msgtransfer.sh:66 openim::msgtransfer::check(...)
  2: ./install/openim-msgtransfer.sh:154 source(...)
  3: ./check-all.sh:80 main(...)
Exiting with status 1

# Begin to check all openim service

## Check all dependent service ports
Checking ports: 13306 16379 12181 19094 37017 10005

### Started ports:
Port 13306 - Command: docker-proxy, PID: 1142542, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 16379 - Command: docker-proxy, PID: 1142111, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 12181 - Command: docker-proxy, PID: 1142158, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 19094 - Command: docker-proxy, PID: 1142284, FD: 4, Started: Fri Oct 20 15:24:03 2023
Port 37017 - Command: docker-proxy, PID: 1146554, FD: 4, Started: Fri Oct 20 15:24:11 2023
Port 10005 - Command: docker-proxy, PID: 1142135, FD: 4, Started: Fri Oct 20 15:24:03 2023
[32m[success 1023 09:51:09] [0m==>  All specified processes are running.

## Check OpenIM service name
!!! [1023 09:51:09] Call tree:
!!! [1023 09:51:09]  1: ./install/openim-msgtransfer.sh:154 openim::msgtransfer::check(...)
!!! [1023 09:51:09]  2: ./check-all.sh:80 source(...)
[31m!!! Error in ./install/openim-msgtransfer.sh:66 [0m
  Error in ./install/openim-msgtransfer.sh:66. '((i<4-1))' exited with status 1
Call stack:
  1: ./install/openim-msgtransfer.sh:66 openim::msgtransfer::check(...)
  2: ./install/openim-msgtransfer.sh:154 source(...)
  3: ./check-all.sh:80 main(...)
Exiting with status 1

```

**Comment by kubbot** [comment]
Hello! Thank you for filing an issue.

If this is a bug report, please include relevant logs to help us debug the problem.

[Join slack 🤖](https://join.slack.com/t/openimsdk/shared_invite/zt-22720d66b-o_FvKxMTGXtcnnnHiMqe9Q) to connect and communicate with our developers.

**Comment by tzhzz0721** [comment]
```
# 执行check-all.sh，有如下异常
## Check OpenIM service name
!!! [1024 09:39:29] Call tree:
!!! [1024 09:39:29]  1: ./install/openim-msgtransfer.sh:154 openim::msgtransfer::check(...)
!!! [1024 09:39:29]  2: ./check-all.sh:80 source(...)
!!! Error in ./install/openim-msgtransfer.sh:66 
  Error in ./install/openim-msgtransfer.sh:66. '((i<4-1))' exited with status 1
Call stack:
  1: ./install/openim-msgtransfer.sh:66 openim::msgtransfer::check(...)
  2: ./install/openim-msgtransfer.sh:154 source(...)
  3: ./check-all.sh:80 main(...)
Exiting with status 1
```

**Comment by skiffer-git** [comment]
Please provide the configuration items for Minio; they are in config/config.yaml

**Comment by tzhzz0721** [comment]
```
# 不能发送音视频的问题已经解决
object:
  enable: "minio"
  apiURL: "http://http://14.153.0.130:10002"
  minio:
    bucket: "openim"
    endpoint: "http://172.28.0.1:10005"
    accessKeyID: "root"
    secretAccessKey: "openIM123"
    sessionToken: ''
    signEndpoint: "http://14.153.0.130:10005"
  cos:
    bucketURL: https://temp-1252357374.cos.ap-chengdu.myqcloud.com
    secretID: ''
    secretKey: ''
    sessionToken: ''
  oss:
    endpoint: "https://oss-cn-chengdu.aliyuncs.com"
    bucket: "demo-9999999"
    bucketURL: "https://demo-9999999.oss-cn-chengdu.aliyuncs.com"
    accessKeyID: ''
    accessKeySecret: ''
    sessionToken: ''
** 问题是apiURL 和 signEndpoint的地址配置错误，我是局域网部署，需要配置为内网ip地址。可以在环境变量中配置IP这个环境变量，然后make init 重启。感谢openim技术人员的支持！！！
```

**Comment by kubbot** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
```
# The problem of not being able to send audio and video has been solved
object:
  enable: "minio"
  apiURL: "http://http://14.153.0.130:10002"
  minio:
    bucket: "openim"
    endpoint: "http://172.28.0.1:10005"
    accessKeyID: "root"
    secretAccessKey: "openIM123"
    sessionToken: ''
    signEndpoint: "http://14.153.0.130:10005"
  cos:
    bucketURL: https://temp-1252357374.cos.ap-chengdu.myqcloud.com
    secretID: ''
    secretKey: ''
    sessionToken: ''
  oss:
    endpoint: "https://oss-cn-chengdu.aliyuncs.com"
    bucket: "demo-9999999"
    bucketURL: "https://demo-9999999.oss-cn-chengdu.aliyuncs.com"
    accessKeyID: ''
    accessKeySecret: ''
    sessionToken: ''
** The problem is that the addresses of apiURL and signEndpoint are configured incorrectly. I am deploying on a LAN and need to configure the intranet IP address. You can configure the IP environment variable in the environment variable, and then restart make init. Thanks to openim technical staff for their support! ! !
```
