### ISSUE TITLE
[Other]:  docker pull ghcr.io/openimsdk/openim-web:latest Error response from daemon: Get "https://ghcr.io/v2/": read tcp 192.168.19.4:38924->20.205.243.164:443: read: connection reset by peer

### ISSUE THREAD

**Issue by 857751635** [openimsdk/open-im-server#1398]
### What would you like to share?

![企业微信截图_16999267801146](https://github.com/openimsdk/open-im-server/assets/10285375/15eacf54-85ed-4be8-99f0-c0a29185411e)
![企业微信截图_16999268055510](https://github.com/openimsdk/open-im-server/assets/10285375/630c6191-da2f-49d3-bcd4-77286b72fce0)
![企业微信截图_16999268402534](https://github.com/openimsdk/open-im-server/assets/10285375/9762bd35-72a7-4d33-8d3b-829da88a61b4)

**Comment by kubbot** [comment]
Hello! Thank you for filing an issue.

If this is a bug report, please include relevant logs to help us debug the problem.

[Join slack 🤖](https://join.slack.com/t/openimsdk/shared_invite/zt-22720d66b-o_FvKxMTGXtcnnnHiMqe9Q) to connect and communicate with our developers.

**Comment by cubxxw** [comment]
Thank you for your inquiry. You can find a lot of documentation on our readme at https://github.com/OpenIMSDK/Open-IM-Server. There are two important sections you should pay attention to: version management strategy and image management strategy. You can refer to the following links for more information:

Version Management Strategy: 
https://github.com/openimsdk/open-im-server/blob/main/docs/contrib/version.md

Image Management Strategy: 
https://github.com/openimsdk/open-im-server/blob/main/docs/contrib/images.md

In the image management strategy section, you will find the corresponding Alibaba Cloud Docker image address. 

To make the necessary modifications, please refer to the docker compose file at:
https://github.com/openimsdk/open-im-server/blob/main/docker-compose.yml

Please pay attention to the comments in the file, such as:

```
openim-web:
    # image: ghcr.io/openimsdk/openim-web:latest
    # image: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-web:latest
    # image: openim/openim-web:latest
    image: ${IMAGE_REGISTRY}/openim-web:latest
    container_name: openim-web
    environment:
      - OPENIM_WEB_DIST_PATH=${OPENIM_WEB_DIST_PATH}
      - OPENIM_WEB_PORT=${OPENIM_WEB_PORT}
    restart: always
    ports:
      - "${OPENIM_WEB_PORT}:11001"
    networks:
      server:
        ipv4_address: ${OPENIM_WEB_NETWORK_ADDRESS}
```

You can set the `IMAGE_REGISTRY` environment variable to the Alibaba Cloud repository address as mentioned in the `.env` file.

Alternatively, you can manually modify it to the Alibaba Cloud address.

If you have any further questions or need assistance, please feel free to ask.
