### ISSUE TITLE
Feature: Streamlining Environment Variable Configuration for Source and Docker Deployments

### ISSUE THREAD

**Issue by cubxxw** [openimsdk/open-im-server#1514]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

✅ Yes

### Problem Description

As a user of this project, I need clear guidance on configuring environment variables for both source code and Docker deployments. The goal is to standardize the configuration process, making it secure, efficient, and easy to manage, regardless of the deployment method.

#### For Source Code Deployment:

1. Environment Variables Setup:
   + Users should set the required environment variables in their local environment.
   + This includes `DB_USER`, `DB_PASSWORD`, `DB_HOST`, and `DB_NAME`.
   + The application will directly read these environment variables.

#### For Docker Deployment:

1. **Utilizing `.env` File**:

   + Provide a `.env.example` file in the repository, which users can copy to create their own `.env` file.
   + The `.env` file should include variables like `DB_USER`, `DB_PASSWORD`, `DB_HOST`, and `DB_NAME`.

2. **Docker Compose Configuration**:

   + Update the `docker-compose.yml` to include services for both the MySQL database and the Go application (`goapp`).
   + The environment variables from the `.env` file should be mapped to both the MySQL service and the Go application service in `docker-compose.yml`.

3. **Sample `docker-compose.yml`**:

   ```yaml
   version: '3'
   services:
     mysql:
       image: mysql:5.7
       ports:
         - "3306:3306"
       environment:
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_DATABASE: ${DB_NAME}
         MYSQL_USER: ${DB_USER}
         MYSQL_PASSWORD: ${DB_PASSWORD}
       volumes:
         - db-data:/var/lib/mysql
   
     goapp:
       build: .
       environment:
         DB_USER: ${DB_USER}
         DB_PASSWORD: ${DB_PASSWORD}
         DB_HOST: mysql
         DB_NAME: ${DB_NAME}
       depends_on:
         - mysql
   
   volumes:
     db-data:
   ```

#### Initialization Script:

+ Implement a `make init` script (or enhance the existing one) to generate both `config.yaml` and `.env` files, facilitating the configuration process.
+ This script should help generate and populate the `.env` file with default values, which users can then modify as needed.

#### For Upgrades:

+ Instruct users to use `docker-compose down` to stop the current running containers.
+ After stopping, users can modify the `.env` file with new account information or other configurations.
+ Then, users can proceed with the upgrade process, possibly using `docker-compose up -d` to start the services with the new configurations.

### Benefits

+ This approach ensures a unified and secure method of configuring environment variables for different deployment scenarios.
+ Enhances the flexibility and scalability of the application deployment, making it easier for users to manage and update configurations.
+ Aligns with industry best practices for environment variable management in both development and production environments.

### Potential Drawbacks

no drawbacks

### Additional Information

+  Update `docker-compose.yml` to reflect the new configuration strategy.
+  Modify or create a `make init` script for easy initialization of configuration files.
+  Update documentation to guide users through the new configuration process.
+  Communicate these changes clearly to the existing user base to ensure a smooth transition.
