### ISSUE TITLE
Bug: change mongo username error

### ISSUE THREAD

**Issue by AndrewZuo01** [openimsdk/open-im-server#1668]
### What happened?

I got Starting Mongo failed, connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.;ths addr is:172.28.0.1:37017

### What did you expect to happen?

mongo should start

### How can we reproduce it (as minimally and precisely as possible)?

change mongo user name to root1 in .env adn config.yaml, (docker compose down already), then change mongo username to root in config/config.yaml, then build and start server

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
Could you please take a look at the fields in the docker-compose.yaml file and the mongo-init.sh script to address this issue? Thank you for your attention to this matter.

```
services:
  mongodb:
    image: mongo:${MONGODB_IMAGE_VERSION-6.0.2}
    ports:
      - "${MONGO_PORT:-37017}:27017"
    container_name: mongo
    command: --wiredTigerCacheSizeGB 1 --auth
    volumes:
      - "${DATA_DIR:-./}/components/mongodb/data/db:/data/db"
      - "${DATA_DIR:-./}/components/mongodb/data/logs:/data/logs"
      - "${DATA_DIR:-./}/components/mongodb/data/conf:/etc/mongo"
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - TZ=Asia/Shanghai
      - wiredTigerCacheSizeGB=1
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-openIM123}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-openIM_v3}
    restart: always
    networks:
      server:
        ipv4_address: ${MONGO_NETWORK_ADDRESS:-172.28.0.2}

```

mongo sh

```

mongo -- "$MONGO_INITDB_DATABASE" <<EOF
db = db.getSiblingDB('admin')
db.auth('$MONGO_INITDB_ROOT_USERNAME', '$MONGO_INITDB_ROOT_PASSWORD')
db = db.getSiblingDB('$MONGO_INITDB_DATABASE')
db.createUser({
  user: "$MONGO_USERNAME",
  pwd: "$MONGO_PASSWORD",
  roles: [
  { role: 'root', db: '$MONGO_INITDB_DATABASE' }
  ]
})
EOF
```
