### ISSUE TITLE
Bug: Docker Network Removal Issue: Unlisted Networks in Docker Network LS Command

### ISSUE THREAD

**Issue by cubxxw** [openimsdk/open-im-server#1829]
### What happened?

The issue involves an inability to remove certain Docker networks, specifically with IP addresses 172.28.0.1, 172.20.0.1, and 172.19.0.1. These networks are not listed when using the 'docker network ls' command, yet they are visible through the 'ifconfig' command. Additionally, the IP address 172.28.0.1 appears twice. This problem is isolated to the user's machine and is not replicated across other team members' machines.

```
root@VM-0-9-ubuntu:/data/openim/openim-docker# docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

docker compose:
```
version: '3'

networks:
  server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${DOCKER_BRIDGE_SUBNET}'
          gateway: '${DOCKER_BRIDGE_GATEWAY}'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    container_name: mysql
    volumes:
      - "${DATA_DIR}/components/mysql/data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    networks:
      server:
        ipv4_address: ${MYSQL_NETWORK_ADDRESS}
```

### What did you expect to happen?

1. The user attempted to remove three Docker networks, but they were not found using the 'docker network ls' command.
2. Network interfaces with the specified IP addresses are listed in the 'ifconfig' output, with 172.28.0.1 appearing twice.
3. The user is working on an open-source Instant Messaging project, making this issue critical for their deployment.

**Investigation and Solution:**

1. The Docker community team suggested checking for possible network creation failures, changes in daemon settings, or manual state removals.
2. The user provided a Docker Compose file they used, indicating a potential issue related to Docker version upgrades.
3. The user's Docker version information was shared.
4. Docker community member @akerouanton provided a solution to manually delete the unlisted networks using commands like `$ sudo ip link del [network-name]`.

### How can we reproduce it (as minimally and precisely as possible)?

I just use docker compose down or up -d, using the above yml file.

Did you have failures when creating new networks (thinking if it possibly created the network "partially", but because of that didn't clean up)
It's possible, but I am not sure. Is there any way I can clean up this network?It could be caused by upgrading the Docker version. Previously, I used docker-compose, but after upgrading Docker, I directly used docker compose.

Did you change any daemon settings at some point (e.g. did you configure --default-address-pool or similar options)?
No

3,. Did you manually remove state (e.g. clean /var/lib/docker)
No

### Anything else we need to know?

The issue has finally been resolved.

```
$ sudo ip link del br-060f06276afb
$ sudo ip link del br-44e4088c44fa
$ sudo ip link del br-5ad852a3ae66
$ sudo ip link del br-d1b3aac5521e
```

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>
