### ISSUE TITLE
[BUG] offlinePush of notification config didn't work

### ISSUE THREAD

**Issue by onenameneo** [openimsdk/open-im-server#2390]
### OpenIM Server Version

3.7

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

目前在项目中我们使用FCM的离线推送，当用户离线时，对用户进行的群操作，比如 邀请进群，openIM会推送离线消息，
![截屏 2024-07-03 17 33 30](https://github.com/openimsdk/open-im-server/assets/6267834/b9b4181f-d711-4c38-90dc-753aa135a5c7)
这个 [NEWMSG] 应该时调用firebase推送入参的 title、desc 都未设置
我们尝试修改了[notification](https://github.com/openimsdk/open-im-server/blob/main/config/notification.yml)的配置
举例：

```yml
memberInvited:
  isSendMsg: true
  reliabilityLevel: 1
  unreadCount: false
  offlinePush:
    enable: false
    title: "memberInvited title"
    desc: "memberInvited desc"
    ext: "memberInvited ext"
```
 
offlinePush中的配置并未生效，**enable** 无论 true 或者 false 都是都会推送离线消息。
  如果修改 **isSendMsg** 为 false，那么这个memberInvited操作在线消息和离线消息都不会发送。

**Comment by kubbot** [comment]
Hello! Thank you for filing an issue.

If this is a bug report, please include relevant logs to help us debug the problem.

[Join slack 🤖](https://join.slack.com/t/openimsdk/shared_invite/zt-22720d66b-o_FvKxMTGXtcnnnHiMqe9Q) to connect and communicate with our developers.

**Comment by printlin** [comment]
Hi, I have thoroughly reviewed the memberInvited handling logic regarding notifications. I can confirm that the offlinePush configuration item in the notification configuration file only uses the enable parameter, and this parameter is loaded but not used. I have replicated your issue and have also fixed it locally; this solution is feasible. I believe there is a design conflict in OpenIM, or the functionality is not fully implemented. It appears that the offline push notifications for system notifications have not been implemented. I am attempting to implement this functionality, which involves a significant amount of work and changes to other projects, so it will take some time.

**Comment by printlin** [comment]
After careful inspection, I found that only minor changes are needed to fix this bug. I have submitted a PR.

**Comment by onenameneo** [comment]
@printlin Hello, we have deployed using the latest version of Docker and tested the offline push configurations for 'memberInvited' and 'memberKicked'. The issue has not been resolved; the offlinePush still do not take effect.
### case 1
```yml
memberInvited:
  isSendMsg: true
  reliabilityLevel: 1
  unreadCount: false
  offlinePush:
    enable: false
    title: "memberInvited title"
    desc: "memberInvited desc"
    ext: "memberInvited ext"
```
offlinePush.enable = false , still get [NEWMSG] offline message

### case 2
```yml
memberInvited:
  isSendMsg: true
  reliabilityLevel: 1
  unreadCount: false
  offlinePush:
    enable: true
    title: "Hi.test title"
    desc: "Hi.test desx"
    ext: "test"
```
still get [NEWMSG] offline message

### case 3
```yml
memberInvited:
  isSendMsg: false
  reliabilityLevel: 1
  unreadCount: false
  offlinePush:
    enable: true
    title: "Hi.test title"
    desc: "Hi.test desx"
    ext: "test"
```
change isSendMsg to false, the message will not be pushed, 'isSendMsg' is worked.
