### ISSUE TITLE
[BUG] 当指定 ATTENTIONIDS 时无法触发 callbackAfterSendSingleMsgCommand 回调

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-server#3321]
### OpenIM Server Version

3.8.3

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

以下是 `docker-compose.yaml` 与 `.env` 文件内容：

```yaml
openim-server:
    environment:
      .......
      - IMENV_WEBHOOKS_AFTERSENDSINGLEMSG_ENABLE=${WEBHOOKS_AFTERSENDSINGLEMSG_ENABLE}
      - IMENV_WEBHOOKS_AFTERSENDSINGLEMSG_TIMEOUT=${WEBHOOKS_AFTERSENDSINGLEMSG_TIMEOUT}
      - IMENV_WEBHOOKS_AFTERSENDSINGLEMSG_ATTENTIONIDS=${WEBHOOKS_AFTERSENDSINGLEMSG_ATTENTIONIDS}
```

以下是 `.env` 文件：

```
WEBHOOKS_AFTERSENDSINGLEMSG_ATTENTIONIDS=["10000","10001","19997"]
```

如果注释掉 `IMENV_WEBHOOKS_AFTERSENDSINGLEMSG_ATTENTIONIDS` 行，回调接口一切正常。
