### ISSUE TITLE
[RFC] Creation and support of Slack for openIM

### ISSUE THREAD

**Issue by cubxxw** [OpenIMSDK/Open-IM-Server#364]
OpenIM's Slack is now open for developers and users to discuss with us, where we integrate AI, and you can ask for help from us and AI. Share your thoughts.
[https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg
)

**Comment by cubxxw** [comment]
insider 作为唯一一个不公布的管道，供内部的开发者邀请进入，请联系我。

**Comment by cubxxw** [comment]
In Slack, you can easily integrate and interact with GitHub. Here are some common operations:
1. Connect to a GitHub account: In Slack's Settings, locate GitHub and add your GitHub username and password to connect to your account. This enables additional integration capabilities.
2. Subscribe to notifications from the repository: After connecting to a GitHub account, you can subscribe to notifications from any public repository and receive Slack notifications when issues, pull requests, or deployment activities occur in that repository. This can be done by typing /github subscribe <owner>/<repo> into Slack.
3. GitHub content will be displayed in Slack: Links to repositories, issues,PR, deployment, etc., will be expanded to show details. You can quickly see what's happening on GitHub without leaving Slack.
4. Reply to GitHub notifications in Slack: For many notifications from GitHub, you can do something in Slack. For example, you can review and approve pull requests, close questions, comment questions, and pull requests in Slack, and so on.
5. Slash command: Use Slash commands like /gh issue create in Slack to create GitHub issues,pull requests, comments, etc.
6. App and workflow integration: The GitHub App Store has a lot for Slack and GitHub

**Comment by cubxxw** [comment]
@skiffer-git In the face of unfriendly direct comments this, the bot can automatically shut down
/invite

**Comment by cubxxw** [comment]
```yaml
name: Invite users to join our group
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Invite users to join our group
    if: ${{ github.event.comment.body == '/invite' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Invite user to join our group
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Your comment body here

        - name: Close issue
          uses: peter-evans/close-issue@v1
          with:
            issue-number: ${{ github.event.issue.number }}
```
