### ISSUE TITLE
Bug: Prometheus Service not start with rpc service

### ISSUE THREAD

**Issue by ling7334** [OpenIMSDK/Open-IM-Server#759]
### What happened?

All rpc service start without prometheus service, even if enabled in config file.

```yaml
###################### Prometheus ######################
# Prometheus configuration
# The number of Prometheus ports per service needs to correspond to rpcPort
# The number of ports needs to be consistent with msg_transfer_service_num in script/path_info.sh
prometheus:
  enable: true
  userPrometheusPort: [ 20110 ]
  friendPrometheusPort: [ 20120 ]
  messagePrometheusPort: [ 20130 ]
  messageGatewayPrometheusPort: [ 20140 ]
  groupPrometheusPort: [ 20150 ]
  authPrometheusPort: [ 20160 ]
  pushPrometheusPort: [ 20170 ]
  conversationPrometheusPort: [ 20230 ]
  rtcPrometheusPort: [ 21300 ]
  thirdPrometheusPort: [ 21301 ]
  messageTransferPrometheusPort: [ 21400, 21401, 21402, 21403 ]
```

prometheusPort is resolved, but service not start

```log
==========================================================
==========================================================
==========================================================
==========server start time:2023-08-02 14:58:05===========
==========================================================
==========================================================
==========================================================
=====================start openim-api======================
configFolderPath: 
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
api start init discov client
api register public config to discov
api register public config to discov success
api init router success
start api server, address:  0.0.0.0:10002 , OpenIM version:  v3.0.0
=====================start openim-rpc-user======================
configFolderPath: 
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start User server, port:  10110 prometheusPort: 0 , OpenIM version:  v3.0.0
mongo: mongodb://<user>:<password>@mongo:27017/openIM_v3?maxPoolSize=100&authSource=admin
=====================start openim-rpc-friend======================
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start Friend server, port:  10120 prometheusPort: 20120 , OpenIM version:  v3.0.0
=====================start openim-rpc-group======================
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start Group server, port:  10150 prometheusPort: 20150 , OpenIM version:  v3.0.0
mongo: mongodb://<user>:<password>@mongo:27017/openIM_v3?maxPoolSize=100&authSource=admin
=====================start openim-rpc-auth======================
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start Auth server, port:  10160 prometheusPort: 20160 , OpenIM version:  v3.0.0
=====================start openim-rpc-msg======================
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start Msg server, port:  10130 prometheusPort: 20130 , OpenIM version:  v3.0.0
mongo: mongodb://<user>:<password>@mongo:27017/openIM_v3?maxPoolSize=100&authSource=admin
=====================start openim-rpc-conversation======================
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start Conversation server, port:  10180 prometheusPort: 20230 , OpenIM version:  v3.0.0
=====================start openim-rpc-third======================
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start Third server, port:  10190 prometheusPort: 21301 , OpenIM version:  v3.0.0
==========================start msg_gateway server===========================
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start rpc/msg_gateway server, port:  10140 10001 20140 , OpenIM version:  v3.0.0
start MessageGateway server, port:  10140 prometheusPort: 0 , OpenIM version:  v3.0.0
==========================start push server===========================
configFolderPath: 
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
start Push server, port:  10170 prometheusPort: 20170 , OpenIM version:  v3.0.0
==========================start msg_transfer server===========================
==========================start msg_transfer server===========================
==========================start msg_transfer server===========================
==========================start msg_transfer server===========================
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
mongo: mongodb://<user>:<password>@mongo:27017/openIM_v3?maxPoolSize=100&authSource=admin
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
configFolderPath: /openim/openim-server/scripts/../config
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
configFolderPath: /openim/openim-server/scripts/../config
mongo: mongodb://<user>:<password>@mongo:27017/openIM_v3?maxPoolSize=100&authSource=admin
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
mongo: mongodb://<user>:<password>@mongo:27017/openIM_v3?maxPoolSize=100&authSource=admin
start msg transfer prometheusPort: 21400
mongo: mongodb://<user>:<password>@mongo:27017/openIM_v3?maxPoolSize=100&authSource=admin
start msg transfer prometheusPort: 21401
start msg transfer prometheusPort: 21403
start msg transfer prometheusPort: 21402
==========================start cron_task process===========================
configFolderPath: 
use config /openim/openim-server/config/config.yaml
use config /openim/openim-server/config/notification.yaml
cron task start, config 0 2 * * 3
mongo: mongodb://<user>:<password>@mongo:27017/openIM_v3?maxPoolSize=100&authSource=admin
```
`netstat -tupln`

```bash
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:40641        0.0.0.0:*               LISTEN      -
tcp        0      0 :::10150                :::*                    LISTEN      141/openim-rpc-grou
tcp        0      0 :::10120                :::*                    LISTEN      111/openim-rpc-frie
tcp        0      0 :::6060                 :::*                    LISTEN      50/openim-api
tcp        0      0 :::10190                :::*                    LISTEN      262/openim-rpc-thir
tcp        0      0 :::10160                :::*                    LISTEN      171/openim-rpc-auth
tcp        0      0 :::10001                :::*                    LISTEN      312/openim-msggatew
tcp        0      0 :::10130                :::*                    LISTEN      201/openim-rpc-msg
tcp        0      0 :::10002                :::*                    LISTEN      50/openim-api
tcp        0      0 :::21400                :::*                    LISTEN      412/openim-msgtrans
tcp        0      0 :::21401                :::*                    LISTEN      413/openim-msgtrans
tcp        0      0 :::21402                :::*                    LISTEN      414/openim-msgtrans
tcp        0      0 :::10170                :::*                    LISTEN      366/openim-push
tcp        0      0 :::21403                :::*                    LISTEN      415/openim-msgtrans
tcp        0      0 :::10140                :::*                    LISTEN      312/openim-msggatew
tcp        0      0 :::10110                :::*                    LISTEN      81/openim-rpc-user
tcp        0      0 :::10180                :::*                    LISTEN      232/openim-rpc-conv
udp        0      0 127.0.0.11:42174        0.0.0.0:*                           -
```

### What did you expect to happen?

prometheus service start to serve and listen to the corresponding port which is define in config

### How can we reproduce it (as minimally and precisely as possible)?

change the Prometheus config and deploy docker image

```yaml
###################### Prometheus ######################
# Prometheus configuration
# The number of Prometheus ports per service needs to correspond to rpcPort
# The number of ports needs to be consistent with msg_transfer_service_num in script/path_info.sh
prometheus:
  enable: true
  userPrometheusPort: [ 20110 ]
  friendPrometheusPort: [ 20120 ]
  messagePrometheusPort: [ 20130 ]
  messageGatewayPrometheusPort: [ 20140 ]
  groupPrometheusPort: [ 20150 ]
  authPrometheusPort: [ 20160 ]
  pushPrometheusPort: [ 20170 ]
  conversationPrometheusPort: [ 20230 ]
  rtcPrometheusPort: [ 21300 ]
  thirdPrometheusPort: [ 21301 ]
  messageTransferPrometheusPort: [ 21400, 21401, 21402, 21403 ]
```

### Anything else we need to know?

maybe change `prome.Enable` to `true` before `prome.StartPrometheusSrv`
https://github.com/OpenIMSDK/Open-IM-Server/blob/d9dbd739ab7b1539af5e81794fba666c39bbeb30/pkg/common/startrpc/start.go#L106

### version

`docker version`

```bash
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:51:04 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:51:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
···

### Cloud provider

<details>
bare metal
</details>


### OS version

`$ cat /etc/os-release`

```yaml
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
`$ uname -a`

```basg
Linux cijiyun.ling.sh 5.10.0-14-cloud-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
```

### Install tools

<details>
</details>
