### ISSUE TITLE
Optimization and Refactoring of Docker and Docker Compose Network Modes

### ISSUE THREAD

**Issue by cubxxw** [OpenIMSDK/Open-IM-Server#995]
# Optimization and Refactoring of Docker and Docker Compose Network Modes

**Description:**

#### Background:

Our current Docker and Docker Compose setups use a bridge network mode. However, there's a need to optimize and refactor the network modes for better scalability, maintainability, and performance.

#### Issue:

Based on our existing `docker-compose.yml` file (see attached), there are areas that can be potentially improved in terms of networking:

1. **Use of Bridge Mode:** While bridge mode is a default and often suitable for many applications, there might be scenarios where host or overlay networking modes may offer better performance or more suitable isolation.
2. **Network Addressing:** Hardcoding IP addresses (e.g., `${MYSQL_NETWORK_ADDRESS}`, `${MONGO_NETWORK_ADDRESS}`, etc.) may not be scalable. We need a more dynamic way of handling this.
3. **Dependency Management:** While `depends_on` is used, we might want to look into the use of `wait-for-it` or similar scripts to ensure services are fully up and ready before dependants start.
4. **Consistency:** Ensure that the network configurations are consistent across all services. For instance, all services should be part of the necessary networks, and network mode should be uniform unless there's a valid reason for deviations.

#### Proposed Action:

1. Evaluate the current bridge mode against our application's needs. Consider if host, overlay, or macvlan modes might be more appropriate.
2. Investigate using Docker's native DNS for service discovery rather than hardcoding IP addresses.
3. Implement `wait-for-it` or similar scripts for better management of service dependencies.
4. Ensure all services have consistent network configurations, including necessary settings for IPv4 and IPv6 (if applicable).
5. Update and refactor the `docker-compose.yml` file based on the findings and proposed changes.

## Content
```
#fixme  Clone openIM Server project before using docker-compose,project address：https://github.com/OpenIMSDK/Open-IM-Server.git
version: '3'

networks:
  openim-server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${DOCKER_BRIDGE_SUBNET}'
          gateway: '${DOCKER_BRIDGE_GATEWAY}'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    container_name: mysql
    volumes:
      - "${DATA_DIR}/components/mysql/data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    networks:
      openim-server:
        ipv4_address: ${MYSQL_NETWORK_ADDRESS}

  mongodb:
    image: mongo:6.0.2
    ports:
      - "${MONGO_PORT}:27017"
    container_name: mongo
    command: --wiredTigerCacheSizeGB 1 --auth
    volumes:
      - "${DATA_DIR}/components/mongodb/data/db:/data/db"
      - "${DATA_DIR}/components/mongodb/data/logs:/data/logs"
      - "${DATA_DIR}/components/mongodb/data/conf:/etc/mongo"
      - "./openim-server/${SERVER_BRANCH}/scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
    environment:
      - TZ=Asia/Shanghai
      - wiredTigerCacheSizeGB=1
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    restart: always
    networks:
      openim-server:
        ipv4_address: ${MONGO_NETWORK_ADDRESS}

  redis:
    image: redis:7.0.0
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${DATA_DIR}/components/redis/data:/data"
      - "${DATA_DIR}/components/redis/config/redis.conf:/usr/local/redis/config/redis.conf"
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    networks:
      openim-server:
        ipv4_address: ${REDIS_NETWORK_ADDRESS}

  zookeeper:
   image: bitnami/zookeeper:3.8
   container_name: zookeeper
   ports:
    - target: 2181
      published: "${ZOOKEEPER_PORT}"
      protocol: tcp
   volumes:
     - "/etc/localtime:/etc/localtime"
   environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     - TZ="Asia/Shanghai"
   restart: always
   networks:
      openim-server:
        ipv4_address: ${ZOOKEEPER_NETWORK_ADDRESS}

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    restart: always
    ports:
    - target: 9092
      published: "${KAFKA_PORT}"
      protocol: tcp
    volumes:
      - ./openim-server/${SERVER_BRANCH}/scripts/create_topic.sh:/opt/bitnami/kafka/create_topic.sh
      # - ${DATA_DIR}/components/kafka/data:/bitnami/kafka/data
    command: >
      bash -c "
      /opt/bitnami/scripts/kafka/run.sh & sleep 30; /opt/bitnami/kafka/create_topic.sh; wait
      "
    environment:
       - KAFKA_CFG_NODE_ID=0
       - TZ=Asia/Shanghai
       - KAFKA_CFG_PROCESS_ROLES=controller,broker
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      openim-server:
        ipv4_address: ${KAFKA_NETWORK_ADDRESS}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:9000"
      - "9090:9090"
    container_name: minio
    volumes:
      - "${DATA_DIR}/components/mnt/data:/data"
      - "${DATA_DIR}/components/mnt/config:/root/.minio"
    environment:
      MINIO_ROOT_USER: "${MINIO_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${MINIO_SECRET_KEY}"
    restart: always
    command: minio server /data --console-address ':9090'
    networks:
      openim-server:
        ipv4_address: ${MINIO_NETWORK_ADDRESS}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openim-web:
    image: ghcr.io/openimsdk/openim-web:latest
    container_name: openim-web
    environment:
      - OPENIM_WEB_DIST_PATH=${OPENIM_WEB_DIST_PATH}
      - OPENIM_WEB_PORT=${OPENIM_WEB_PORT}
    restart: always
    ports:
      - "${OPENIM_WEB_PORT}:11001"
    networks:
      openim-server:
        ipv4_address: ${OPENIM_WEB_NETWORK_ADDRESS}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openim-server:
    # image: ghcr.io/openimsdk/openim-server:${SERVER_BRANCH}
    image: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-server:${SERVER_BRANCH}
    # image: openim/openim-server:${SERVER_BRANCH}
#    build: .
    container_name: openim-server
    ports:
      - ${OPENIM_WS_PORT}:10001
      - ${API_OPENIM_PORT}:10002
    healthcheck:
      test: ["CMD", "/openim/openim-server/scripts/check-all.sh"]
      interval: 300s
      timeout: 10s
      retries: 5
    volumes:
      - ./openim-server/logs:/openim/openim-server/logs
      - ./openim-server/_output:/openim/openim-server/_output
      - ./openim-server/${SERVER_BRANCH}/config:/openim/openim-server/config
      - ./openim-server/${SERVER_BRANCH}/scripts:/openim/openim-server/scripts
    restart: always
    depends_on:
      - kafka
      - mysql
      - mongodb
      - redis
      - minio
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
    networks:
      openim-server:
        ipv4_address: ${OPENIM_SERVER_NETWORK_ADDRESS}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openim-chat:
    # image: ghcr.io/openimsdk/openim-chat:${CHAT_BRANCH}
    image: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-chat:${CHAT_BRANCH}
    # image: ghcr.io/openimsdk/openim-chat:${CHAT_BRANCH}
    container_name: openim-chat
    healthcheck:
      test: ["CMD", "/openim/openim-chat/scripts/check_all.sh"]
      interval: 300s
      timeout: 10s
      retries: 5
    ports:
      - ${OPENIM_CHAT_API_PORT}:10008
      - ${OPENIM_ADMIN_API_PORT}:10009
    volumes:
      - ./openim-chat/logs:/openim/openim-chat/logs
      - ./openim-chat/_output:/openim/openim-chat/_output
      - ./openim-chat/${CHAT_BRANCH}/config:/openim/openim-chat/config
      - ./openim-chat/${CHAT_BRANCH}/scripts:/openim/openim-chat/scripts
    restart: always
    user: root:root
    depends_on:
      - mysql
      - mongodb
      - redis
      - minio
      - openim-server
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
    networks:
      openim-server:
        ipv4_address: ${OPENIM_CHAT_NETWORK_ADDRESS}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./openim-server/${SERVER_BRANCH}/.docker-compose_cfg/prometheus-compose.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT}:9091
    depends_on:
      - openim-server
    command: --web.listen-address=:9091 --config.file="/etc/prometheus/prometheus.yml"
    networks:
      openim-server:
        ipv4_address: ${PROMETHEUS_NETWORK_ADDRESS}

  grafana:
    image: grafana/grafana
    volumes:
      - ./openim-server/${SERVER_BRANCH}/.docker-compose_cfg/datasource-compose.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./openim-server/${SERVER_BRANCH}/.docker-compose_cfg/grafana.ini:/etc/grafana/grafana.ini
      - ./openim-server/${SERVER_BRANCH}/.docker-compose_cfg/node-exporter-full_rev1.json:/var/lib/grafana/dashboards/node-exporter-full_rev1.json
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:3000
    depends_on:
      - prometheus
    networks:
      openim-server:
        ipv4_address: ${GRAFANA_NETWORK_ADDRESS}

  # node-exporter:
  #   image: quay.io/prometheus/node-exporter
  #   container_name: node-exporter
  #   restart: always
  #   ports:
  #     - "9100:9100"
```
